# Verbs: get, list, create, update, patch, watch, delete, and deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-deployments
  namespace: default
rules:
  - apiGroups: [ apps ]
    resources: [ deployments ]
    verbs: [ get, list, update, patch, watch ]
  - apiGroups: [ apps ]
    resources: [ replicasets ]
    verbs: [ get, list, update, patch, watch ]
  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get, list, update, patch, watch ]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restart-deployments-pods
  namespace: default
subjects:
- kind: User
  name: idl-support
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: restart-deployments
  apiGroup: rbac.authorization.k8s.io
